services:
  docker-dotnet-ui:
    build:
      context: .
      dockerfile: Docker.Dotnet.UI/Dockerfile
    image: docker-dotnet-ui:latest
    container_name: docker-dotnet-ui
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # 挂载 Docker socket 以便容器内可以控制宿主机 Docker
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Production
    #   - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    # 如果在 Windows 上运行，可能需要不同的 socket 路径
    # 对于 Windows + WSL2，上面的配置应该可以正常工作

